import { readdir, writeFile } from 'fs/promises';
import path from 'path';

const petSkinsArrayGenerator = async () => {
  // error in line 7 and 24: "process" not defined (works in node, no problem)
  // eslint-disable-next-line
  const parentFolder = path.join(process.cwd(), 'public', 'petSprites');

  const folders = (await readdir(parentFolder)).sort();

  const output = `//! AUTO-GENERATED FILE
 //* Generated by @/utils/scripts/petSkinsArrayGenerator.js
 
 //? To recreate skins:
 // 1. open "/proyecto 12/utils/petSpriteScraper" in terminal
 // 2. npm run start - wait for it to finish
 // 3. open "/proyecto 12" (main project root) in terminal
 // 4. npm run generateSkins, this file will be rewritten with current skins :)


const petSkins = ${JSON.stringify(folders, null, 2)};

export default petSkins
`;

  // eslint-disable-next-line
  const outputFile = path.join(process.cwd(), 'src', 'data', 'petSkins.js');

  await writeFile(outputFile, output);

  console.log('Pet skins array generated in @/data/petSkins :D');
};

petSkinsArrayGenerator();
